name: "ci"

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
    lint:
        timeout-minutes: 30
        runs-on: "ubuntu-latest"
        steps:
            - name: checkout repository
              uses: actions/checkout@v3

            - name: setup
              uses: ./.github/actions/devenv
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  nix-cache: /tmp/nixcache

            - name: lint
              run: lint:all
              shell: bash

    build:
        timeout-minutes: 30
        runs-on: "ubuntu-latest"
        steps:
            - name: checkout repository
              uses: actions/checkout@v3

            - name: setup
              uses: ./.github/actions/devenv
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  nix-cache: /tmp/nixcache

            - name: build
              run: build:kickjump_com
              shell: bash

            - name: get installed playwright version
              id: playwright-version
              run: |
                  TEMP_VERSION=`pnpm playwright -V | sed -e "s/Version //"`
                  echo "PLAYWRIGHT_VERSION=$TEMP_VERSION" >> $GITHUB_ENV
              shell: bash

            - name: cache playwright binaries
              uses: actions/cache@v3
              id: playwright-cache
              with:
                  path: |
                      ~/.cache/ms-playwright
                  key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

            - name: install playwright browsers and dependencies
              run: pnpm playwright install --with-deps
              if: steps.playwright-cache.outputs.cache-hit != 'true'
              shell: bash

            - name: install playwright dependencies
              run: pnpm playwright install-deps
              if: steps.playwright-cache.outputs.cache-hit == 'true'
              shell: bash

            - name: test
              run: test:kickjump_com
              shell: bash
